export const FAKE_ACTIVITY_DATA = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    interaction: 5,
    time: 10,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    interaction: 8,
    time: 20,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    interaction: 6,
    time: 15,
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    interaction: 7,
    time: 18,
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    interaction: 4,
    time: 12,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Diana Wilson",
    email: "diana.wilson@example.com",
    interaction: 9,
    time: 25,
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Eva Lee",
    email: "eva.lee@example.com",
    interaction: 3,
    time: 8,
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "Frank Harris",
    email: "frank.harris@example.com",
    interaction: 6,
    time: 16,
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Grace Clark",
    email: "grace.clark@example.com",
    interaction: 10,
    time: 30,
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Hank Lewis",
    email: "hank.lewis@example.com",
    interaction: 2,
    time: 5,
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 11,
    name: "Ivy Walker",
    email: "ivy.walker@example.com",
    interaction: 7,
    time: 19,
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 12,
    name: "Jack Young",
    email: "jack.young@example.com",
    interaction: 4,
    time: 13,
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 13,
    name: "Kara King",
    email: "kara.king@example.com",
    interaction: 5,
    time: 14,
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 14,
    name: "Liam Scott",
    email: "liam.scott@example.com",
    interaction: 6,
    time: 17,
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 15,
    name: "Mia Adams",
    email: "mia.adams@example.com",
    interaction: 8,
    time: 22,
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 16,
    name: "Noah Carter",
    email: "noah.carter@example.com",
    interaction: 3,
    time: 9,
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 17,
    name: "Olivia Green",
    email: "olivia.green@example.com",
    interaction: 9,
    time: 26,
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: 18,
    name: "Paul Baker",
    email: "paul.baker@example.com",
    interaction: 7,
    time: 21,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 19,
    name: "Quinn Evans",
    email: "quinn.evans@example.com",
    interaction: 6,
    time: 15,
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Rita Hall",
    email: "rita.hall@example.com",
    interaction: 5,
    time: 13,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 21,
    name: "Sam Allen",
    email: "sam.allen@example.com",
    interaction: 4,
    time: 12,
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 22,
    name: "Tina Wright",
    email: "tina.wright@example.com",
    interaction: 9,
    time: 28,
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 23,
    name: "Ursula Murphy",
    email: "ursula.murphy@example.com",
    interaction: 7,
    time: 19,
    image: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    id: 24,
    name: "Victor Rivera",
    email: "victor.rivera@example.com",
    interaction: 6,
    time: 17,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: 25,
    name: "Wendy Mitchell",
    email: "wendy.mitchell@example.com",
    interaction: 8,
    time: 23,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
];
